name: windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >- # using example here: https://github.com/msys2/setup-msys2/blob/main/examples/cmake.yml
            git
            make
            bison
            flex
          pacboy: >- # `:p` suffix installs the package for the current environment only.
            toolchain:p
            cmake:p
            ninja:p
            boost:p
            cgal:p
            eigen3:p
            glew:p
            qscintilla:p
            opencsg:p
            libzip:p
            double-conversion:p
            cairo:p
            ghostscript:p
            imagemagick:p
            qt5-svg:p
            qt5-multimedia:p
      - name: Install Mesa
        uses: ssciwr/setup-mesa-dist-win@v1
        with:
          build-type: 'release-mingw'
      - name: Build OpenSCAD
        run: |
          git submodule update --init --recursive
          mkdir build && cd build
          cmake .. -G"Ninja" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON
          cmake --build . -j2
      - name: Run Test Suite
        run: |
          cd build
          cd tests
          ctest -j2 -E 'opencsgtest_issue1165|opencsgtest_issue1215|throwntogethertest_issue1089|throwntogethertest_issue1215|openscad-nonascii|import_3mf|3mfpngtest|3mfexport|pdfexporttest_centered'
      - name: Upload Test Result Report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Test Result Report (Windows)
          path: |
            build/tests/Testing/Temporary/*_report.html
            build/tests/Testing/Temporary/LastTest.log
